### ISSUE TITLE
The head and tail might move away from each other

### ISSUE THREAD

**Issue by murjam** [martinleis/wormapp#2]
When pressing down and right arrow-buttons at once, something like shown on the picture can happen.
![worm_fail_screenshot](https://cloud.githubusercontent.com/assets/4026737/6337362/06bb23ee-bbb2-11e4-9aa3-e61e9109a2e7.png)

**Comment by martinr55** [comment]
Solved with commit 00b3d944683ded18827a98e7b5c18dbf9130170f.
